### ISSUE TITLE
README lists the wrong name for the "check" script

### ISSUE THREAD

**Issue by lachmacn-at-medibank** [akuroda/teradata-udf-sha2#1]
README lists:
- sha256test_chck.sql
- sha512test_chck.sql

It should read:
- sha256test_chk.sql
- sha512test_chk.sql

**Comment by akuroda** [comment]
Thanks for your report!

**Comment by lachmacn-at-medibank** [comment]
Thanks for your UDF ☺

Lachlan Macnish
BI Platform Administrator, EDWBI Support – Medibank IT
T +61 3 8622 5586 E lachlan.macnish@medibank.com.aumailto:lachlan.macnish@medibank.com.au
