### ISSUE TITLE
CASE statement in sha256test_chk.sql not output to BTEQ output.

### ISSUE THREAD

**Issue by lachmacn-at-medibank** [akuroda/teradata-udf-sha2#2]
When running "sha256test_chk.sql" in BTEQ, the output of the CASE statment ("OK"/"NG") is not displayed, thought it does display in SQL Assistant

Example:

.run file = sha256test_chk.sql
 BTEQ -- Enter your SQL request or BTEQ command:
/\* check sha256 result against test data */

sel
i,
hash_sha256(input_data),
case
 when hash_sha256(input_data) = output_data then 'OK'
 else 'NG'
end as "result"
from
sha256_test
order by 1;

 **\* Query completed. 130 rows found. 3 columns returned.
 **\* Total elapsed time was 4 seconds.

```
      i hash_sha256(input_data)
```

---

```
      0 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b85
      1 ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48b
      2 961b6dd3ede3cb8ecbaacbd68de040cd78eb2ed5889130cceb4c49268ea4d50
      3 9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f
      4 61be55a8e2f6b4e172338bddf184d6dbee29c98853e0a0485ecee7f27b9af0b
```

**Comment by akuroda** [comment]
Did you try .SET WIDTH 1000?
